export const ADMIN_TABLES = [
  "partners",
  "announcements",
  "gallery_items",
  "assessment_reports",
  "contact_submissions",
  "profiles",
];

export const adminSeed = {
  partners: [
    {
      partner_name: "植本邏輯 高雄健康據點",
      city: "高雄市",
      category: "健康顧問",
      contact_name: "品牌顧問",
      phone: "07-223-2301",
      email: "bryan@phytologic.tw",
      website_url: "https://phytologic.tw",
      description: "提供植物機能飲品體驗、健康需求初談與 Dr.Marvin 快篩導入服務。",
      status: "approved",
    },
    {
      partner_name: "台北試飲活動合作窗口",
      city: "台北市",
      category: "活動據點",
      contact_name: "林小姐",
      phone: "02-0000-0000",
      email: "partner@example.com",
      description: "申請中的試飲活動合作據點，用於示範審核流程。",
      status: "pending",
    },
  ],
  announcements: [
    {
      title: "植本邏輯官方網站籌備啟動",
      category: "品牌活動",
      summary: "以品牌形象、產品教育、Dr.Marvin 與合作加盟為核心，建立完整官方資訊入口。",
      content: "官方網站將整合創辦理念、產品教育、Dr.Marvin、加盟合作與最新活動資訊。",
      status: "published",
      is_pinned: true,
      published_at: "2026-05-18T00:00:00.000Z",
    },
    {
      title: "LINE 會員與 AI 健康推薦系統開發中",
      category: "系統開發",
      summary: "以生活狀態與快篩結果建立每日飲品建議。",
      content: "第一階段將以 LINE 作為會員入口，導入 Dr.Marvin 快篩與飲品推薦。",
      status: "draft",
      is_pinned: false,
    },
  ],
  gallery_items: [
    {
      title: "品牌試飲交流",
      type: "photo",
      category: "活動現場",
      media_url: "/logo.png",
      thumbnail_url: "/logo.png",
      description: "示範精彩剪影資料，正式上線後可改由 Supabase Storage 管理圖片。",
      status: "published",
      published_at: "2026-05-18T00:00:00.000Z",
    },
  ],
  assessment_reports: [
    {
      gender: "女性",
      age_group: "35-44",
      bmi: 22.4,
      total_score: 18,
      inflammation_level: "輕度失衡",
      recommended_products: ["青檸植萃"],
      has_joined_line: true,
      ai_analysis: "壓力、睡眠與飲食節奏可能是目前較需要優先調整的方向。",
      lifestyle_advice: "今天先把晚餐提前 30 分鐘，並補足水分。",
      answers: [],
      system_scores: { digestion: 4, immune: 3, sleep: 3 },
    },
  ],
  contact_submissions: [
    {
      name: "王小姐",
      phone: "0900-000-000",
      email: "hello@example.com",
      type: "企業健康方案",
      message: "想了解企業試飲與健康講座合作方式。",
      status: "unread",
    },
  ],
  profiles: [],
};
