-- ============================================================
-- Dr. Marvin question_bank seed
-- Source: 01_DOCS/dr-marvin/DR_MARVIN_KNOWLEDGE_BASE.md
-- Generated: 2026-06-02
--
-- Notes:
--   - Seed only. Requires public.question_bank to exist.
--   - Uses seven canonical system_category values from AGENTS.md task.
--   - All questions use frequency scoring: 0 / 1 / 2.
-- ============================================================

do $$
begin
  if to_regclass('public.question_bank') is null then
    raise exception 'public.question_bank does not exist. Run supabase/dr_marvin_question_engine.sql before this seed.';
  end if;

  alter table public.question_bank
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now(),
    add column if not exists is_active boolean not null default true;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'question_bank_unique_question'
      and conrelid = 'public.question_bank'::regclass
  ) then
    alter table public.question_bank
      add constraint question_bank_unique_question
      unique (system_category, age_groups, gender_filter, question_text);
  end if;
end $$;

insert into public.question_bank
(system_category, age_groups, gender_filter, question_text, question_type, options, weight, priority)
values
  ('brain_nerve', ARRAY['teen'], 'all', '常常覺得疲勞，睡醒之後沒有精力充沛，或是還想再睡？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '覺得晚上睡得不夠或睡眠品質不好，或有黑眼圈？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '白天（例如上課、搭車時）容易打瞌睡？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '注意力不集中，難以全神貫注或堅持完成作業？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '記憶力減退、常忘東忘西（例如掉東西、忘記剛才要說什麼）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '經常頭暈或頭痛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '覺得無緣無故感到沮喪，對過去喜愛的事物失去動機和興趣？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '比平時更焦慮、擔心，或有莫名恐慌、心神不寧的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '經歷無法解釋的情緒波動（易怒、煩躁）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '說話時常叫錯名字，或表達出錯？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '對聲音、光線或觸覺有不正常的敏感或排斥？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '眼睛比較怕強光，或容易畏光？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '眼睛乾澀、容易發癢，或晨起有眼屎？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '經常消化不良或有腹脹的問題？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '肚子時常有悶痛、鈍痛、刺痛，或手壓下去會不舒服？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '經常腹脹或脹氣（肚子在飯後膨脹）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '大便比較稀，或是難以控制的稀水便？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '有便祕狀況（超過 24 小時沒排便，或糞便乾硬如羊便便）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '經常經歷交替性的腹瀉和便祕？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '有噁心或想吐的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '進食後，會感到胃痛或胃痙攣？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '經歷緊張、考試、恐慌或焦慮時，會感到胃部不適或腹瀉？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '太久沒進食或進食後，出現心口灼熱或胃酸逆流？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '舌頭上是否覆蓋著看起來模糊的白厚舌苔？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '口腔黏膜乾燥，或常有破洞疼痛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['teen'], 'all', '一年內感冒三次以上？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['teen'], 'all', '一年內曾有氣喘發作？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['teen'], 'all', '身體比較容易過敏（如起風疹塊、打噴嚏、流鼻水、咳嗽）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['teen'], 'all', '被蚊子叮咬後，腫脹沒有在兩天之內消退？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['teen'], 'all', '皮膚有濕疹、異位性皮膚炎、牛皮癬等狀況？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['teen'], 'all', '皮膚容易發癢、粗糙或增厚？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['teen'], 'all', '臉部或身體有不明原因的疹子，或是慢性、反覆發作的嚴重青春痘？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['teen'], 'all', '對某些食物（如乳製品、麩質）產生極端的反應（如腹瀉、疼痛、皮膚起疹）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['teen'], 'all', '雙手或雙腳有不明原因的搔癢、脫皮或起疹子？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['teen'], 'all', '傷口癒合極度緩慢？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('muscle_bone', ARRAY['teen'], 'all', '肌肉或關節經常發痠或發疼？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '關節疼痛（週期性、不斷痛來痛去）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '容易發生意外？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '時常扭傷腳踝、跌倒或拉傷肌腱/韌帶？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '關節是否容易過度活動（感覺關節超靈活或鬆散）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '關節是否不斷地發出喀喀響、劈啪響？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '運動後舒緩的僵硬或疼痛，隔天狀況又再度復發？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '有慢性的頸部或背部疼痛、緊繃、緊張感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '雙手和雙腳有刺痛、隨機刺痛或麻木無感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '按摩會感到異常疼痛（尤其是雙臂、腿部）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '爬樓梯比較沒力氣、容易喘？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '脖子和後腦勺有痠脹感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['teen'], 'all', '經常渴望含糖或澱粉類食物（吃過正餐後還想吃甜點）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['teen'], 'all', '注意到最近食慾大幅增加，或經常口渴且排尿增加？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['teen'], 'all', '視力經常模糊？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['teen'], 'all', '異常疲倦，即使有足夠睡眠，但只有在吃東西後才能短暫緩解？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['teen'], 'all', '當幾小時沒有進食時，會感到頭重腳輕、發抖、煩躁或「餓極成怒」（生氣）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['teen'], 'all', '腰圍是否等於或大於臀圍（肚子微凸）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['teen'], 'all', '身體容易保留水分（水腫），在某些日子看起來浮腫或小腹凸出？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['teen'], 'all', '體重在幾天內劇烈波動超過 2 公斤？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['teen'], 'all', '尿液是否容易呈現深黃色？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['teen'], 'all', '是否有一種「中毒」或身體極度沉重的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['teen'], 'all', '容易在下午出現疲憊或頭痛，然後晚上又精神好起來，造成熬夜？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['teen'], 'all', '突然站起來時，會頭暈目眩？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['teen'], 'all', '時常渴望吃鹹的食物？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['teen'], 'all', '即使環境溫暖，依然常覺得手腳冰冷？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['teen'], 'all', '修整眉毛時，發現外側三分之一變得稀疏或缺失？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['teen'], 'all', '身體內部感覺到發痠、發麻、發冷、發熱等不明疼痛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['teen'], 'all', '臉頰、額頭、胸前容易有潮熱（微微發紅發熱）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['teen'], 'all', '刷牙時牙齦容易出血？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['teen'], 'all', '指甲比較脆弱、容易剝落，或有橫紋/縱紋？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['teen'], 'all', '一年內有流鼻血狀況？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['teen'], 'all', '腳後跟皮膚很粗糙？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['teen'], 'all', '半夜會起床小便兩次以上？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['teen'], 'all', '小便有灼熱感、尿道發癢或頻尿？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['teen'], 'all', '休息時感覺到心臟在跳（心悸）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['teen'], 'all', '休息時依然有極度、不斷、持續的疲憊，無法藉由睡眠緩解？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['teen'], 'female', '【限女性】月經不規則、疼痛或流量異常大？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['teen'], 'female', '【限女性】經血太少或太多，或生理期情緒極度暴躁？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['teen'], 'male', '【限男性】經常感覺陰囊或睪丸區域有不舒服或悶痛感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('brain_nerve', ARRAY['young_adult'], 'all', '常常覺得疲勞，睡醒之後仍沒有精力充沛，或還想再睡？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '覺得晚上睡眠時間不夠或睡眠品質不好，眼周常有黑眼圈？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '白天上課、開會或搭車時，容易不受控制地打瞌睡？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '注意力不集中，出現「腦霧」，難以全神貫注或堅持完成一項任務？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '記憶力減退，常忘東忘西（例如忘記剛才要說什麼、掉東西）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '經常有頭暈或頭痛的毛病？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '有失眠、多夢或淺眠的問題？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '覺得無緣無故感到沮喪，對過去喜愛的事物失去動機和興趣？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '比平時更焦慮、擔心，或有莫名恐慌、心神不寧的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '經歷無法解釋的強烈情緒波動（如易怒、暴躁）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '說話時常叫錯名字，或在表達時頻繁出錯？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '對日常的聲音、光線或觸覺感到異常敏感或排斥？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '眼睛容易畏光，或對螢幕光線感到刺眼？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '休息時感覺到心臟在異常跳動（心悸），且並非因運動引起？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('brain_nerve', ARRAY['young_adult'], 'all', '經常感到神經緊繃，無法徹底放鬆休息？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '經常有消化不良、吃飽後食積不化的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '肚子時常有悶痛、鈍痛、刺痛，或手壓下去會感到不舒服？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '時常有噁心或想吐的感覺（排除懷孕因素）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '經常在進食後或兩餐之間，肚子膨脹得像懷孕（嚴重脹氣）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '經常有腹瀉，或是難以控制的稀水便？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '超過二十四小時沒有排便的狀況？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '排放的糞便常常乾硬如羊屎（便祕）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '經常交替性出現腹瀉和便祕（腸躁症傾向）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '當太久沒進食或進食後，會感到心口灼熱或胃酸逆流？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '舌頭上常覆蓋著一層看起來模糊的白厚舌苔（脾胃濕熱）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '進食後，經常會感到胃痛或胃痙攣？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '經歷緊張、考試、恐慌或焦慮時，會立刻感到胃部不適或引發腹瀉？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '口腔黏膜乾燥，或經常有破洞疼痛（嘴破）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '刷牙時牙齦非常容易發炎、紅腫或出血？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['young_adult'], 'all', '嘴唇常覺得乾燥脫皮，或嘴角容易破裂發炎？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '一年內健檢肝指數曾超標，或曾被診斷有輕度脂肪肝？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('detox_liver', ARRAY['young_adult'], 'all', '身體容易保留水分，在某些日子看起來浮腫，或小腹有異常的緊緻微凸感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '體重在幾天之內劇烈波動超過兩公斤（組織液滯留）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '常常有一種「中毒」、沉重或身體極度不清爽的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('detox_liver', ARRAY['young_adult'], 'all', '曾注意到自己的膚色或眼白微泛黃？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '似乎有與進食無關的腹部壓痛，甚至擴散到右背部或肩膀（膽囊發炎徵兆）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '尿液經常呈現深黃色，或大便顏色經常變淺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '雙手或雙腳上有不明原因的搔癢、脫皮或起疹子？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '皮膚容易發癢、粗糙或異常增厚？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '臉頰、額頭、胸前容易出現潮紅（微發紅發熱）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '經常性感到口乾舌燥、早晨起床覺得口苦？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '眼睛經常乾澀、容易發癢，或晨起有異常多的眼屎？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '原本正常的髮量，最近卻非常容易掉頭髮？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '指甲變得比較脆弱、容易剝落，或出現明顯的橫紋與縱紋？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '腳後跟皮膚異常粗糙或嚴重龜裂？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['young_adult'], 'all', '經常極度渴望含糖或澱粉類食物（例如吃完正餐一定要吃甜點）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['young_adult'], 'all', '注意到最近食慾異常增加，總是覺得吃不飽？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '經常感到口渴，且排尿量明顯增加？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['young_adult'], 'all', '視力經常模糊，且時好時壞？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['young_adult'], 'all', '異常疲倦，即使有足夠睡眠，但只有在「吃東西後」才能短暫緩解？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['young_adult'], 'all', '當幾小時沒有進食時，會感到頭重腳輕、發抖、搖晃或「餓極成怒」（生氣煩躁）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['young_adult'], 'all', '腰圍等於或大於臀圍，肚子上的脂肪特別難減？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['young_adult'], 'all', '遭遇嚴重的減重抗性，即使減少卡路里或運動，體重依然毫無動靜？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['young_adult'], 'all', '健檢曾檢測過空腹血糖數值異常（達 100 dl/ml 或更高）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('blood_sugar_cardio', ARRAY['young_adult'], 'all', '爬樓梯稍微活動就覺得沒力氣、容易喘，體能大幅下降？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['young_adult'], 'all', '容易在下午出現疲憊或頭痛，然後晚上又精神好起來，造成習慣性熬夜？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['young_adult'], 'all', '突然從座位上站起來時，會感到嚴重的頭暈目眩（姿勢性低血壓）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['young_adult'], 'all', '時常強烈渴望吃極度重鹹的食物？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['young_adult'], 'all', '即使環境溫暖，依然常覺得手腳冰冷？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['young_adult'], 'all', '修整眉毛時，發現外側三分之一變得稀疏或缺失（甲狀腺功能異常徵兆）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['young_adult'], 'all', '性衝動或性慾顯著消失或減退？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '半夜常需要起床小便兩次以上？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['young_adult'], 'all', '小便時有灼熱感、尿道發癢或頻尿？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['young_adult'], 'all', '有靜脈曲張的問題或腿部常冒出青筋？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['young_adult'], 'all', '身體內部常感覺到發冷、發熱、發寒等溫度調節失常的問題？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['young_adult'], 'female', '【限女性】月經不規則、有間歇性出血，或疼痛流量異常大？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['young_adult'], 'female', '【限女性】經血太少，或生理期情緒極度暴躁、經前症候群（PMS）嚴重？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['young_adult'], 'female', '【限女性】平時有白色或黃色分泌物，甚至帶有異味？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['young_adult'], 'male', '【限男性】清晨勃起的頻率顯著減少（一週少於三次）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['young_adult'], 'male', '【限男性】勃起的時間變短、硬度不夠，或行房容易早洩？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('muscle_bone', ARRAY['young_adult'], 'all', '肌肉或關節經常發痠、發疼或僵硬？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'all', '關節常有不明原因的疼痛（週期性、不斷痛來痛去，似乎與受傷無關）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'all', '關節是否容易過度活動（感覺關節過度鬆散或有「雙重關節」現象）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'all', '容易發生意外，時常扭傷腳踝、跌倒，或拉傷肌腱與韌帶？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'all', '關節是否不斷地發出喀喀響或劈啪聲？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'all', '運動後舒緩的僵硬或疼痛，結果到隔天狀況又再度劇烈復發（嚴重延遲性肌肉痠痛）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'all', '慢性且長期無法緩解的頸部或背部疼痛、緊繃、緊張感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'all', '脖子和後腦勺經常有難以消除的痠脹感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'all', '肢體或皮膚常常覺得發麻？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'all', '雙手和雙腳有刺痛、隨機刺痛或完全麻木無感覺的狀況？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'all', '按摩時會感到異常疼痛（尤其是雙臂、腿部），稍微按壓就受不了？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['young_adult'], 'female', '【限女性】行房時感覺乾燥或伴隨疼痛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('muscle_bone', ARRAY['young_adult'], 'female', '【限女性】月經來身體很不舒服或感覺子宮/骨盆腔周圍極度虛弱、悶痛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('muscle_bone', ARRAY['young_adult'], 'male', '【限男性】行房之後身體極度虛弱、不舒服，甚至容易感冒？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('muscle_bone', ARRAY['young_adult'], 'male', '【限男性】平時陰莖根部與肛門之間（會陰部）有痠脹甚至疼痛的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('immune', ARRAY['young_adult'], 'all', '免疫力低下，一年內感冒三次以上，或感染後遲遲好不了？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['young_adult'], 'all', '被蚊子叮咬後，紅腫脹大且沒有在兩天之內消退？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['young_adult'], 'all', '身體非常容易過敏（例如頻繁起風疹塊、打噴嚏、流鼻水、咳嗽）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['young_adult'], 'all', '皮膚有濕疹、異位性皮膚炎、牛皮癬等慢性狀況？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['young_adult'], 'all', '臉部或身體有不明原因的疹子、慢性反覆發作的嚴重青春痘（痤瘡）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['young_adult'], 'all', '只要吃特定的食物（如乳製品、麩質）就會產生明顯的極端反應（如腹瀉、疼痛、皮膚起疹或腦霧）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['young_adult'], 'all', '身體不時覺得忽冷忽熱，或出現無感染跡象的微發燒？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['young_adult'], 'all', '經常感覺身體兩側（例如雙手、雙肘、雙膝）出現對稱性的關節疼痛或腫脹？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['young_adult'], 'all', '經歷極度的、不斷的、持續的疲憊，無法藉由睡眠、飲食或休假來緩解？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['young_adult'], 'all', '有不明原因的肌肉無力，或者經常感覺拖著腳步走路？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['young_adult'], 'all', '上述的過敏或發炎反應是突發性的（突然發作、持續幾天後消退，幾週後又再度復發）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['young_adult'], 'all', '一年內曾有氣喘發作的紀錄？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['young_adult'], 'all', '傷口癒合速度極度緩慢，或容易化膿發炎？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['young_adult'], 'all', '一年內曾有不明原因的流鼻血？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['young_adult'], 'male', '【限男性】睪丸有脹脹、沉重或痠痛的感覺（精索靜脈曲張/發炎徵兆）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '常常覺得疲勞，睡醒之後依然覺得沒有精力充沛，或還想再睡？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '覺得晚上睡眠時間不夠或品質不好，眼周經常有黑眼圈？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '白天開車、開會或上班時，容易不受控制地打瞌睡？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '注意力不集中（腦霧），難以全神貫注或堅持完成一項任務？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '記憶力明顯減退，常忘東忘西（例如忘記交代的事、找不到鑰匙）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '經常有頭暈或頭痛的毛病？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '覺得無緣無故感到沮喪，對過去喜愛的事物失去動機和興趣？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '比平時更焦慮、擔心，或有莫名恐慌、心神不寧的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '經歷無法解釋的強烈情緒波動（如易怒、暴躁、缺乏耐性）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '說話時常叫錯名字，或在表達時頻繁出錯、詞不達意？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '對日常的聲音、光線或觸覺感到異常敏感或排斥？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '眼睛經常乾澀、容易發癢，或畏懼強光？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '有耳鳴的毛病（且非外傷或器官受損引起）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '休息時感覺到心臟在異常跳動（心悸），且並非運動引起？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '經常感到神經緊繃，即使休假也無法徹底放鬆休息？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '經常有消化不良、吃飽後食積不化、胃脹的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '肚子時常有悶痛、鈍痛、刺痛，或手壓下去會感到不舒服？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '經常在進食後或兩餐之間，肚子膨脹得像懷孕（嚴重脹氣）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '時常有噁心或想吐的感覺（排除懷孕因素）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '經常有腹瀉，或是難以控制的稀水便？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '超過二十四小時沒有排便的狀況？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '排放的糞便常常乾硬如羊屎（便祕）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '經常交替性出現腹瀉和便祕（腸躁症傾向）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '當太久沒進食或進食後，會感到心口灼熱或胃酸逆流？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '舌頭上常覆蓋著一層看起來模糊的白厚舌苔（中醫指的脾胃濕熱）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '進食後，經常會感到胃痛或胃痙攣？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '經歷緊張、工作死線（Deadline）或焦慮時，會立刻感到胃部不適或引發腹瀉？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '口腔黏膜經常乾燥，或常有破洞疼痛（反覆嘴破）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '刷牙時牙齦非常容易發炎、紅腫或出血（維生素C缺乏與微血管發炎徵兆）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['middle_adult'], 'all', '吃高油脂或炸物時，容易感到腸胃極度沉重不適或引發腹瀉？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('detox_liver', ARRAY['middle_adult'], 'all', '身體容易保留水分，在某些日子看起來浮腫，或小腹有異常的緊緻微凸感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '體重在幾天之內劇烈波動超過兩公斤（組織液滯留型水腫）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '常常有一種「中毒」、沉重或身體極度不清爽的疲累感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('detox_liver', ARRAY['middle_adult'], 'all', '曾注意到自己的膚色暗沉、蠟黃，或眼白微泛黃？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '似乎有與進食無關的腹部壓痛，甚至擴散到右背部或肩膀（膽囊發炎徵兆）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '尿液經常呈現深黃色，或大便顏色經常變淺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '雙手或雙腳上有不明原因的搔癢、脫皮或起疹子？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '臉頰、額頭、胸前容易出現潮紅（微發紅發熱）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '原本正常的髮量，近年卻發現非常容易掉頭髮或髮際線後退？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '指甲變得比較脆弱、容易剝落，或出現明顯的橫紋與縱紋？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '腳後跟皮膚異常粗糙或嚴重龜裂？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '健檢時肝指數（AST/ALT）曾超標，或曾被診斷有輕度脂肪肝？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('detox_liver', ARRAY['middle_adult'], 'all', '容易長體痘、汗皰疹或蕁麻疹等皮膚排毒異常現象？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '經常感到口乾舌燥，尤其是早晨起床覺得口苦？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '經常需要極度依賴咖啡因或提神飲料，否則無法維持日常運作？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '經常極度渴望含糖或澱粉類食物（例如吃完正餐一定要吃甜點或喝手搖飲）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '注意到最近食慾異常增加，總是覺得吃不飽？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '經常感到口渴，且排尿量明顯增加？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['middle_adult'], 'all', '視力經常模糊，且時好時壞？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '異常疲倦，即使有足夠睡眠，但只有在「吃東西後」才能短暫緩解？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '當幾小時沒有進食時，會感到頭重腳輕、發抖、搖晃或「餓極成怒」（因飢餓而發脾氣）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '腰圍等於或大於臀圍（中年發福、內臟脂肪堆積）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '遭遇嚴重的減重抗性，即使減少卡路里或努力運動，體重依然毫無動靜？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '健檢曾檢測過空腹血糖數值異常（達 100 dl/mL 或更高），或糖化血色素（HbA1c）達 5.7 以上？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '吃飽飯後容易陷入昏昏欲睡的「食睏」狀態，無法集中精神？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '爬樓梯稍微活動就覺得沒力氣、容易喘，體能大幅下降？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '血液檢查中，三酸甘油酯（TG）偏高，或高密度脂蛋白（HDL）偏低？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '曾被醫師警告有膽固醇超標或動脈硬化的早期風險？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['middle_adult'], 'all', '容易在下午出現疲憊或頭痛，晚上卻又精神好起來，造成習慣性熬夜？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '突然從座位上站起來時，會感到嚴重的頭暈目眩（姿勢性低血壓）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['middle_adult'], 'all', '時常強烈渴望吃極度重鹹的食物？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['middle_adult'], 'all', '即使環境溫暖，依然常覺得手腳冰冷（氣血循環不良）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['middle_adult'], 'all', '修整眉毛時，發現外側三分之一變得稀疏或缺失（甲狀腺功能異常徵兆）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['middle_adult'], 'all', '性衝動或性慾顯著消失或減退？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['middle_adult'], 'all', '半夜常需要起床小便兩次以上（夜尿）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('detox_liver', ARRAY['middle_adult'], 'all', '小便時有灼熱感、尿道發癢、頻尿，或小腹有痠脹感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['middle_adult'], 'all', '身體內部常感覺到發冷、發熱、發寒等溫度調節失常的問題？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['middle_adult'], 'female', '【女性】月經開始不規則、有間歇性出血，或疼痛、流量異常大？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['middle_adult'], 'female', '【女性】經血太少，或生理期情緒極度暴躁、經前症候群（PMS）加重？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['middle_adult'], 'female', '【女性】平時有白色或黃色分泌物，甚至帶有異味？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['middle_adult'], 'female', '【女性】行房時感覺乾燥或伴隨疼痛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['middle_adult'], 'male', '【男性】清晨勃起的頻率顯著減少（一週少於三次）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['middle_adult'], 'male', '【男性】勃起的時間變短、硬度不夠，或行房容易早洩？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['middle_adult'], 'male', '【男性】平時陰莖根部與肛門之間（會陰部）有痠脹、沉重甚至疼痛的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['middle_adult'], 'male', '【男性】行房之後身體極度虛弱、不舒服，甚至容易感冒？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '肌肉或關節經常發痠、發疼或僵硬？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '關節常有不明原因的疼痛（週期性、不斷痛來痛去，似乎與受傷無關）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '關節是否容易過度活動（感覺關節過度鬆散或有「雙重關節」現象）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '容易發生意外，時常扭傷腳踝、跌倒，或拉傷肌腱與韌帶？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '關節活動時不斷地發出喀喀響或劈啪聲？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '運動後舒緩的僵硬或疼痛，結果到隔天狀況又再度劇烈復發（嚴重延遲性肌肉痠痛）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '有慢性且長期無法緩解的頸部、肩部或下背部疼痛與緊繃感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '脖子和後腦勺經常有難以消除的痠脹感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '肢體或皮膚常常覺得發麻？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '雙手和雙腳有刺痛、隨機刺痛或麻木無感覺的狀況？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '按摩時會感到異常疼痛（尤其是雙臂、腿部），稍微按壓就受不了？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '有靜脈曲張的問題，或腿部經常冒出青筋？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['middle_adult'], 'all', '運動耐力明顯變差，以前能輕鬆完成的運動現在做起來非常吃力？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['middle_adult'], 'all', '免疫力低下，一年內感冒三次以上，或感染後遲遲好不了？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['middle_adult'], 'all', '一年內曾有氣喘發作的紀錄？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['middle_adult'], 'all', '身體非常容易過敏（例如頻繁起風疹塊、打噴嚏、流鼻水、咳嗽）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['middle_adult'], 'all', '被蚊子叮咬後，紅腫脹大且沒有在兩天之內消退？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['middle_adult'], 'all', '皮膚有濕疹、異位性皮膚炎、牛皮癬等慢性狀況？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['middle_adult'], 'all', '臉部或身體有不明原因的疹子、慢性反覆發作的嚴重成人痘（痤瘡）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['middle_adult'], 'all', '只要吃特定的食物（如乳製品、麩質）就會產生明顯的極端反應（如腹瀉、疼痛、皮膚起疹）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['middle_adult'], 'all', '經常覺得忽冷忽熱，或感覺到沒有感冒跡象的微發燒？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['middle_adult'], 'all', '經常感覺身體兩側（例如雙手、雙肘、雙膝）出現對稱性的關節疼痛或腫脹？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['middle_adult'], 'all', '經歷極度的、不斷的、持續的全身性疲憊，無法藉由睡眠、飲食或休假來緩解？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['middle_adult'], 'all', '上述的過敏或發炎狀態常是突發的（突然發作、持續幾天後消退，幾週後又再度復發）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['middle_adult'], 'all', '傷口癒合速度極度緩慢，或非常容易化膿發炎？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('brain_nerve', ARRAY['senior'], 'all', '常常覺得疲勞，睡醒之後依然覺得沒有精力充沛，甚至有越睡越累的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '睡眠品質大幅變差，容易早醒、多夢，或半夜頻繁醒來難以入睡？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '白天（如看電視、看報紙、搭車時）很容易不自覺地打瞌睡？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '記憶力明顯衰退，常忘記剛剛要做什麼，或頻繁找不到鑰匙、眼鏡等物品？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '注意力難以集中，思考變得遲鈍，有一種「腦霧」的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '經常頭暈、頭重腳輕，或有不明原因的頭部脹痛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '學習新事物的能力明顯下降，對原本感興趣的周遭事物失去動力？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '容易焦慮、恐慌，或時常感到莫名的心神不寧？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '情緒波動大，變得容易不耐煩或暴躁易怒？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '說話時常常「話到嘴邊想不起來」或頻繁叫錯人名？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '對日常的聲音、光線變得異常敏感，覺得吵鬧難以忍受？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '眼睛容易畏光、乾澀、視力模糊，或常出現飛蚊症現象？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '經常有耳鳴的毛病（且非外傷或耳朵器官受損引起）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['senior'], 'all', '休息時感覺到心臟在異常跳動（心悸），且並非運動引起？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('brain_nerve', ARRAY['senior'], 'all', '即使沒有特別的壓力事件，神經也常常處於緊繃、無法放鬆的狀態？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '經常消化不良，吃飽後覺得胃部脹滿、食積不化？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '肚子時常有悶痛、鈍痛、刺痛，或是手按壓時會感到不舒服？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '飯後或兩餐之間，肚子經常膨脹得很大（嚴重脹氣）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '經常有反胃、噁心或想吐的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '大便形狀改變，經常有稀水便或不成形的腹瀉？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '排便困難，超過一天以上才排便，或必須依賴藥物/偏方才能排便？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '糞便經常乾硬如羊屎狀（便祕）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '腹瀉與便祕交替發生（腸躁症傾向）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '吃完飯或空腹太久時，容易感到心口灼熱或胃酸逆流？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '舌頭上經常覆蓋著厚白或黃色的舌苔（中醫指的脾胃濕熱）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '吃完特定食物（如麵包、牛奶）後，容易腸胃絞痛或痙攣？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '面對壓力或緊張時，腸胃會立刻感到不適或想跑廁所？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '口腔黏膜乾燥，或經常反覆發生嘴破（口腔潰瘍）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '刷牙時牙齦非常容易發炎、紅腫或出血（牙周病前兆，也是全身微血管發炎徵兆）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['senior'], 'all', '吃太油膩的食物時，容易引發腹痛或腹瀉？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '身體容易水腫，尤其是下肢、腳踝，或早晨臉部、眼皮浮腫？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '體重常在幾天內忽上忽下波動超過一到兩公斤（水分與組織液滯留）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '經常覺得身體像「中毒」一樣，有一種極度沉重、不清爽的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('detox_liver', ARRAY['senior'], 'all', '皮膚暗沉、長出斑點（老人斑），或眼白部分出現微泛黃現象？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '腹部右上方（肝膽區）偶爾有悶痛，甚至延伸到右肩背（膽囊發炎警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '尿液經常呈現深黃色，或是大便顏色經常變灰白？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '皮膚經常出現不明原因的搔癢、脫皮、起疹子或增厚？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '臉頰、額頭或胸前容易出現不明原因的潮紅發熱？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '掉髮量明顯增加，髮際線後退，或髮質變得非常脆弱乾枯？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '指甲變得脆弱易斷，或表面出現明顯的直紋、凹陷？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '腳後跟皮膚異常粗糙、嚴重角質化或龜裂？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '健檢報告顯示肝指數（GOT/GPT）偏高，或被診斷有脂肪肝？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('detox_liver', ARRAY['senior'], 'all', '容易長體痘、汗皰疹，或覺得體味、老人味變重？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '早晨起床時經常覺得口乾、口苦或有嚴重的口臭？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '以前可以喝一點酒，現在變得很容易宿醉，或對酒精/咖啡因耐受度大幅下降？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '吃完正餐後，仍然極度渴望吃甜點或精緻碳水化合物？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '容易覺得吃不飽，食量比以前大，但吃完又容易覺得疲倦？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '經常覺得口乾舌燥，且排尿次數異常頻繁？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '健檢報告曾顯示空腹血糖異常，或糖化血色素（HbA1c）偏高？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '幾個小時沒吃東西就會頭暈、手抖、心慌或暴躁易怒（低血糖與胰島素不穩反應）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '體型改變，腰圍變粗、肚子變大（內臟脂肪明顯增加）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '不論怎麼少吃或運動，體重都降不下來（遭遇嚴重減重抗性）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '飯後常常感到極度睏倦（食睏），完全無法集中精神做事？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '爬一層樓梯或稍微快走就會覺得胸悶、氣喘吁吁，體力大不如前？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '健檢發現三酸甘油酯（TG）偏高、或壞膽固醇（LDL）超標？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '曾被醫師提醒有血壓偏高，或已經開始服用高血壓藥物？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '脖子或後腦勺經常覺得僵硬、緊繃、有脹痛感（血管壓力警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '手指或腳趾末端常常覺得冰冷，甚至有發麻感（末梢血管循環不良）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '久坐站起時，經常感到頭暈目眩（姿勢性低血壓）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['senior'], 'all', '腿部經常有靜脈曲張浮現，或常常覺得下肢沉重痠痛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '下午常出現疲憊頭痛，到了晚上卻又精神亢奮難以入睡（腎上腺疲勞）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['senior'], 'all', '對溫度的調節變差，常覺得忽冷忽熱，或是不正常流汗？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['senior'], 'all', '眉毛外側三分之一變得稀疏或掉落（甲狀腺功能減退警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['senior'], 'all', '感覺性慾明顯下降，或對伴侶失去興趣？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['senior'], 'all', '夜間常需起床尿尿超過兩次以上（夜尿嚴重干擾睡眠）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['senior'], 'all', '即使氣溫溫暖，仍常覺得全身發冷或手腳冰冷？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['senior'], 'all', '突然特別想吃極度重鹹或重口味的食物？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['senior'], 'female', '【限女性】月經週期已開始不規律、經血量異常改變，或已停經？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['senior'], 'female', '【限女性】容易出現熱潮紅、盜汗、心悸等更年期症狀？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['senior'], 'female', '【女性】陰道或生殖器附近常感乾燥、瘙癢，或行房時感到疼痛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['senior'], 'female', '【女性】小腹偶爾有悶痛，或曾被診斷有子宮肌瘤、卵巢囊腫？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('endocrine_hormone', ARRAY['senior'], 'male', '【限男性】清晨勃起的次數明顯減少（一週少於三次）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['senior'], 'male', '【男性】勃起硬度不足、持久度下降，或有早洩現象？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['senior'], 'male', '【男性】排尿變得不順暢、尿流變細、滴尿，或有尿不乾淨的感覺（攝護腺肥大/發炎警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['senior'], 'male', '【男性】會陰部（睪丸與肛門之間）經常有痠脹、沉重或疼痛感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('muscle_bone', ARRAY['senior'], 'all', '早上起床時，常覺得全身關節僵硬、活動不順暢（晨僵現象）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '肌肉或關節經常發痠、疼痛，且會「跑來跑去」痛不同的地方？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '肩頸、下背部或腰部有慢性、長期無法緩解的痠痛與緊繃感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '關節活動時（如蹲下、轉動肩膀），經常發出喀喀的摩擦聲響？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '以前能輕鬆做的動作（如手舉高穿衣、梳頭），現在覺得困難或疼痛（五十肩前兆）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '運動或勞動後產生的肌肉痠痛感，需要好幾天甚至一週以上才能恢復？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '稍微提重物或姿勢不對，就非常容易閃到腰、拉傷肌肉或扭傷韌帶？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '按摩時，稍微按壓手臂或腿部肌肉就會覺得異常疼痛難忍？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '手腳常常有刺痛感、螞蟻爬的感覺，或甚至麻木失去知覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '握力變差，常常覺得手使不上力或容易把東西掉落？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '關節曾經或正在經歷紅、腫、熱、痛的發炎反應？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '發現自己的肌肉量明顯減少，肉變得鬆垮無力（肌少症風險）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '膝蓋爬樓梯或下坡時會感到痠軟無力或明顯疼痛（退化性關節炎警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '足底經常疼痛，尤其是早晨下床走的第一步最痛（足底筋膜炎）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['senior'], 'all', '身體內部常常有一種說不出的痠、麻、冷、熱交替的不適感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['senior'], 'all', '免疫力變差，一年感冒超過三次，或感冒後咳嗽拖很久才好？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['senior'], 'all', '原本沒有過敏，這幾年突然對某些食物、花粉或氣味產生過敏反應？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['senior'], 'all', '皮膚受傷或被蚊蟲叮咬後，紅腫很難消退，甚至容易化膿、留下深色疤痕？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['senior'], 'all', '反覆發生尿道炎、膀胱炎、念珠菌感染或呼吸道感染？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['senior'], 'all', '皮膚經常莫名長出濕疹、蕁麻疹、牛皮癬或不明紅疹？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['senior'], 'all', '身體兩側（如雙手關節、雙膝）出現對稱性的關節腫痛（類風濕性關節炎先兆）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['senior'], 'all', '經常覺得身體處於「微發燒」或忽冷忽熱的狀態，量體溫卻又正常？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['senior'], 'all', '一年內曾發生過氣喘，或經常覺得呼吸不順暢、胸口有壓迫感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['senior'], 'all', '曾經發作過帶狀皰疹（皮蛇），或在疲累時容易復發單純皰疹（唇皰疹）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('immune', ARRAY['senior'], 'all', '常常有一種極度的、無法用休息或睡眠來緩解的全身性疲倦，感覺身體內部一直在耗損？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('brain_nerve', ARRAY['elder'], 'all', '記憶力明顯衰退，常忘記剛剛發生的事，或頻繁找不到重要物品？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '常常在熟悉的社區或街道感到迷失方向，或忘記如何回家？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '睡眠品質極差，清晨很早就醒來，且半夜醒來後難以再入睡？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '白天坐著看電視、看報紙或搭車時，非常容易不受控制地打瞌睡？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '思考變得遲鈍，有一種「腦霧」的感覺，無法集中精神？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '說話時常常「話到嘴邊想不起來」，或頻繁叫錯親友的名字？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '手部在靜止休息時會出現不自覺的顫抖（巴金森氏症前兆警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '經常有頭暈、頭重腳輕，或走路時覺得平衡感變差？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '情緒波動大，變得容易猜忌、固執、缺乏耐性或暴躁易怒？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '對原本感興趣的社交活動失去動力，變得不想出門或與人交談？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '聽力明顯退化，或經常有耳鳴的毛病（非耳朵器官受損引起）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '眼睛容易畏光、乾澀、發癢，或常出現飛蚊症現象？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('brain_nerve', ARRAY['elder'], 'all', '視力模糊，或曾被醫師診斷有白內障、黃斑部病變或青光眼的風險？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('brain_nerve', ARRAY['elder'], 'all', '休息時感覺到心臟異常跳動（心悸），或常有無名恐慌感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('brain_nerve', ARRAY['elder'], 'all', '常常覺得極度疲勞，睡醒之後依然覺得沒有精力充沛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('digestive', ARRAY['elder'], 'all', '經常消化不良，吃飽後覺得胃部脹滿、食物一直停在胃裡下不去？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '牙齒鬆動脫落、咀嚼困難，或戴假牙常感到牙齦疼痛發炎？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '刷牙時牙齦非常容易紅腫、出血（牙周病是全身血管發炎的指標）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '口腔黏膜乾燥，唾液分泌變少，或經常反覆發生嘴破（口腔潰瘍）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '舌頭上經常覆蓋著厚厚的白苔或黃苔（中醫指的脾胃濕熱）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '經常有反胃、噁心，或吃油膩食物後想吐的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '飯後或兩餐之間，肚子經常膨脹得很大（嚴重脹氣）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '肚子時常有悶痛、鈍痛，或是手按壓時會感到不舒服？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '排便困難，經常超過兩天以上才排便，或必須依賴軟便藥物？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '糞便經常乾硬如羊屎狀，用力排便時容易引發頭暈或血壓上升？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '大便形狀改變，經常有稀水便、不成形的腹瀉，或大便黏馬桶？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '腹瀉與便祕交替發生，腸胃極度敏感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('digestive', ARRAY['elder'], 'all', '吃完飯或躺下時，容易感到心口灼熱、胸悶或胃酸逆流？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('digestive', ARRAY['elder'], 'all', '吃進特定食物（如牛奶、小麥製品）後，容易腸胃絞痛或拉肚子？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('digestive', ARRAY['elder'], 'all', '曾被檢查出大腸息肉，或大便中帶有血絲/呈現黑色？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '身體容易水腫，尤其是小腿、腳踝按下去會凹陷，或早晨臉部浮腫？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '經常覺得身體像「中毒」一樣，有一種極度沉重、四肢無力的感覺？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('detox_liver', ARRAY['elder'], 'all', '尿液經常呈現深黃色、有難聞異味，或是尿液表面常常有很多泡泡且久久不散？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '臉部或手背的「老人斑」、黑斑在近期突然大量增加或顏色變深？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '膚色暗沉、蠟黃，或眼白部分出現微泛黃現象？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '腹部右上方（肝膽區）偶爾有悶痛，甚至延伸到右肩背部？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '皮膚經常出現不明原因的搔癢、脫皮，或皮膚變得像羊皮紙一樣薄且乾燥？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '指甲變得非常脆弱易斷，或表面出現明顯的直紋、凹陷？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '腳後跟皮膚異常粗糙、嚴重角質化或龜裂流血？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '健檢報告顯示肝指數（GOT/GPT）偏高，或被診斷有脂肪肝？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('detox_liver', ARRAY['elder'], 'all', '腎功能指標（如 eGFR 腎絲球過濾率）出現紅字或逐漸下降？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '容易長出汗皰疹、不明紅疹，或覺得身上的體味、老人味變重？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '早晨起床時經常覺得口乾、口苦，或有嚴重的口臭？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '頭髮變得非常稀疏、脆弱，或大量掉髮？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '對於以前常吃的西藥（如止痛藥、感冒藥），現在吃完容易覺得肝腎沉重或極度疲倦？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '健檢報告曾顯示空腹血糖異常，或糖化血色素（HbA1c）大於 6.0？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('detox_liver', ARRAY['elder'], 'all', '經常覺得口乾舌燥，喝很多水卻還是覺得渴，且排尿次數異常頻繁？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '幾個小時沒吃東西就會頭暈、手抖、心慌、冒冷汗（低血糖與胰島素不穩反應）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '吃完正餐後，仍然非常渴望吃甜食或精緻糕點？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '體型改變，四肢變細但腰圍變粗、肚子變大（內臟脂肪明顯增加）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '爬一層樓梯或稍微快走就會覺得胸悶、心臟無力、氣喘吁吁？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '健檢發現三酸甘油酯（TG）偏高、或壞膽固醇（LDL-C）超標？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '已經確診高血壓，或血壓經常忽高忽低難以控制？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '脖子或後腦勺經常覺得僵硬、緊繃、有脹痛感（血管壓力警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '手指或腳趾末端常常覺得冰冷，甚至有發麻、感覺遲鈍的現象（末梢神經/血管發炎）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '久坐、久蹲站起時，經常感到嚴重的頭暈目眩、眼前發黑（姿勢性低血壓）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '腿部經常有靜脈曲張浮現，或常常覺得下肢沉重痠痛？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '身上稍微碰撞就容易出現大片瘀青，且很久才消退（微血管脆弱發炎）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '傷口癒合速度極度緩慢，一個小擦傷都要好幾個星期才會結痂？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('blood_sugar_cardio', ARRAY['elder'], 'all', '曾經有過短暫的說話不清、半邊臉或手腳突然無力（小中風警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '早上起床時，常覺得全身關節僵硬、難以伸展，需要活動一段時間才緩解（晨僵現象）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '發現自己的肌肉量明顯減少，肉變得鬆垮無力，毛巾擰不乾或罐頭打不開（肌少症警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '膝蓋爬樓梯、下坡或蹲下時，會感到痠軟無力或明顯疼痛（退化性關節炎）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '肌肉或關節經常發痠、疼痛，且會「跑來跑去」痛不同的地方？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '肩頸、下背部或腰椎有慢性、長期無法緩解的痠痛與僵硬感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '關節活動時（如轉動肩膀、屈伸膝蓋），經常發出喀喀的摩擦聲響？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '以前能輕鬆做的動作（如手舉高穿衣、梳頭），現在覺得困難或伴隨劇痛（五十肩）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '稍微提重物、彎腰或姿勢不對，就非常容易閃到腰或拉傷肌肉？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '按摩時，稍微按壓手臂或腿部肌肉就會覺得異常疼痛難忍？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '走路步伐變小、速度變慢，或常常覺得腳拖著地走，容易絆倒跌跤？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '從比較矮的沙發或馬桶站起來時，覺得非常吃力，必須用手撐著？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '關節曾經或正在經歷紅、腫、熱、痛的發炎反應？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '經常在半夜睡覺時發生小腿抽筋（電解質不平衡與肌肉發炎）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '足底經常疼痛，尤其是早晨下床走的第一步最痛（足底筋膜炎）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('muscle_bone', ARRAY['elder'], 'all', '曾被醫師診斷有骨質疏鬆症，或曾經因為輕微跌倒就發生骨折？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('detox_liver', ARRAY['elder'], 'all', '夜間常需起床尿尿超過兩次以上，嚴重干擾睡眠品質（夜尿）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['elder'], 'male', '【男性】排尿變得不順暢、尿流變細、滴尿，或有尿不乾淨的感覺（攝護腺肥大/發炎警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['elder'], 'male', '【男性】會陰部（睪丸與肛門之間）或下腹部經常有痠脹、沉重或悶痛感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('detox_liver', ARRAY['elder'], 'female', '【女性】大笑、咳嗽或打噴嚏時，會有漏尿的現象（骨盆底肌鬆弛）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 7),
  ('endocrine_hormone', ARRAY['elder'], 'female', '【女性】陰道或生殖器附近常感極度乾燥、瘙癢，或常有反覆的泌尿道感染？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('detox_liver', ARRAY['elder'], 'all', '小便時有灼熱感、尿道發癢、頻尿，或尿液顏色混濁？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['elder'], 'all', '即使氣溫溫暖，仍常覺得全身發冷或極度怕冷？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('endocrine_hormone', ARRAY['elder'], 'all', '眉毛外側三分之一變得稀疏或掉落（甲狀腺功能減退警訊）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('detox_liver', ARRAY['elder'], 'all', '下午常出現疲憊頭痛，到了晚上卻又精神亢奮難以入睡（腎上腺疲勞）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('endocrine_hormone', ARRAY['elder'], 'all', '突然特別想吃極度重鹹或重口味的食物？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['elder'], 'all', '免疫力變差，一年感冒超過三次，或感冒後咳嗽、疲累拖很久才好？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['elder'], 'all', '曾經發作過「帶狀皰疹（皮蛇）」，或在疲累時非常容易復發單純皰疹（唇皰疹）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('immune', ARRAY['elder'], 'all', '經常覺得身體處於「微發燒」或忽冷忽熱的狀態，量體溫卻又正常？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['elder'], 'all', '一年內曾發生過氣喘，或經常覺得呼吸不順暢、胸口有壓迫感？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['elder'], 'all', '喉嚨經常有清不完的痰，或早晨起床會連續咳嗽？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['elder'], 'all', '原本沒有過敏，老後突然對某些食物、灰塵或氣味產生強烈過敏反應？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['elder'], 'all', '皮膚受傷或被蚊蟲叮咬後，紅腫極難消退，甚至容易化膿發炎？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['elder'], 'all', '皮膚經常莫名長出濕疹、蕁麻疹、牛皮癬或不明紅疹？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['elder'], 'all', '身體兩側（如雙手指關節、雙膝）出現對稱性的關節紅腫痛（類風濕性關節炎先兆）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['elder'], 'all', '曾被醫師抽血檢查出免疫發炎指標（如 CRP、白血球數值）異常偏高？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['elder'], 'all', '常常有一種極度的、無法用休息或睡眠來緩解的全身性疲倦，感覺身體內部一直在耗損？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 8),
  ('immune', ARRAY['elder'], 'all', '經常有不明原因的流鼻血，或牙齦無故流血？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['elder'], 'all', '身體容易對溫差改變產生劇烈反應（如一吹冷風就瘋狂打噴嚏流鼻水）？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5),
  ('immune', ARRAY['elder'], 'all', '患有慢性疾病（如糖尿病、高血壓），且經常需要服用多種藥物來壓制症狀？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 9),
  ('immune', ARRAY['elder'], 'all', '近期體重在沒有刻意減肥的情況下，出現不明原因的快速下降？', 'frequency', '[{"label":"從不發生","score":0},{"label":"偶爾發生","score":1},{"label":"經常發生","score":2}]'::jsonb, 1.00, 5)
on conflict on constraint question_bank_unique_question do update set
  question_type = excluded.question_type,
  options = excluded.options,
  weight = excluded.weight,
  priority = excluded.priority,
  is_active = true,
  updated_at = now();

-- Verification helper after running seed:
-- select system_category, count(*) from public.question_bank group by system_category order by system_category;
-- select unnest(age_groups) as age_group, count(*) from public.question_bank group by age_group order by age_group;
